@port = 3000
@url = http://localhost:{{port}}

### POST SETTINGS
POST {{url}}/settings
Content-Type: application/json

{
  "chat": true,
  "username": "isabela"
}

### POST USERS
POST {{url}}/users
Content-Type: application/json

{
  "email": "email2@email.com"
}
